# Generated by Django 5.1.4 on 2025-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_question_options_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-total_score', '-highest_score', 'last_attempt_date'], 'verbose_name': 'Leaderboard', 'verbose_name_plural': 'Leaderboard'},
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='topic',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='total_attempted_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='highest_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
